server:
  port: 8080
  #所以请求url加上前缀路径
  servlet:
    context-path: /druid

#Druid连接池配置
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/ctest?useUnicode=true&characterEncoding=utf-8
      username: root
      password: mysql
      #初始化连接数
      initial-size: 1
      #最小连接数
      min-idle: 1
      #最大连接数
      max-active: 10
      #获取连接等待超时时间，毫秒
      max-wait: 10000
      #一个连接在连接池中最小生存时间，毫秒
      min-evictable-idle-time-millis: 300000
      #与检查间隔时间配合,true时,达到时间,执行validation-query查询语句,判断连接是否有效
      test-while-idle: true
      #用户检查连接的查询语句
      validation-query: select 1
      #检查关闭空闲连接的间隔时间，毫秒
      time-between-eviction-runs-millis: 60000
       #申请连接时,查询连接有效性
      test-on-borrow: false
      #归还连接时,查询连接有效性
      test-on-return: false
      #字符串别名方式,配置扩展插件,stat:监控统计,wall:防sql注入,log4j:日志
      filters: stat,wall,log4j
      #Oracle下配置,缓存preparedStatement
      #pool-prepared-statements: false
      #max-pool-prepared-statement-per-connection-size: 0

#Mybatis配置
mybatis:
  # 注意：一定要对应mapper映射xml文件的所在路径
  mapper-locations: classpath:mapping/*.xml
  # 注意：对应实体类的路径
  type-aliases-package: com.example.druidmodule.entity

#Pagehelper分页插件配置
pagehelper:
    #数据库方言,告诉插件用的什么数据库
    helperDialect: mysql
    #pageNum<1显示第1页 pageNum>pages显示最后1页
    reasonable: true
    #可在mapper中生效
    supportMethodsArguments: true
    #自定义属性名,可不改,其他page属性：pageNum,pageSize,count,total,pages
    params: count=countSql



